### ISSUE TITLE
Help with a Gaofen 6 image

### ISSUE THREAD

**Issue by pablomandolesi** [desertstsung/Project_JiaoTang#1]
Hello, i´m pablo mandolesi from Argentina.  I don´t know if it is pertinent to write here, but i need to ask for your help.
I´m trying to incorporate a Gaofen 6 WFV image to my work in envi and I haven´t been able to do it. The extension stops after decompresing the tgz file. A sing pops up saying "ERROR: Required arguments are missing". I have the tgz file. About the the DEM it says it´s optional so i left it blank. I´ve tried with a DEM of mine also. i didn´t use a shapefile to mask because i didn´t want to add some variable that could add an error like having different proyection than the image or something. I´ve tried using the "PIE Ortho" and "PCI Geomatics" software. I don´t know what else to do. 
It would be amazing if you or anyone could help me. If you like to write to me, my mail is pablomandolesi@hotmail.com Twitter: @pablomandolesi

**Comment by desertstsung** [comment]
im sorry to tell you that im now working on this project in IDL8.3/ENVI5.1 environment, so i cant help you to find what kind of error occurs(since this extension reqiures ENVI5.3). if you cant wait for the next release, you can find and install the extension named '中国国产卫星支持工具' in ENVI APP Store to help you fulfil your task.

**Comment by PabloMandolesi** [comment]
Thanks a lot for your help. I´ll do that!

**Comment by pablomandolesi** [comment]
Thanks a lot for your help. I´ll do that!
